### ISSUE TITLE
support qwen models?

### ISSUE THREAD

**Issue by xxm1668** [Kedreamix/Linly-Talker#1]

**Comment by Kedreamix** [comment]
of course, I'll update my project soon!

**Comment by Kedreamix** [comment]
**2024.01 Update 📆📆**

Exciting news! I've now incorporated both the powerful **GeminiPro** and **Qwen** large models into our conversational scene. Users can now upload images during the conversation, adding a whole new dimension to the interactions.

**Comment by xxm1668** [comment]
thanks
