### ISSUE TITLE
想问一下作者，这个可以用多卡进行推理吗

### ISSUE THREAD

**Issue by kkkwjr** [Kedreamix/Linly-Talker#100]

**Comment by Kedreamix** [comment]
你好，我暂时没有增加多卡推理的代码，但是他是可以的，比如每一部分都可以分开，但是我代码里面暂时没有优化

**Comment by Crescentz** [comment]
实测， 8卡H100无法正常推理

**Comment by Kedreamix** [comment]
你好，无法正常推理是什么意思，其实一卡就能跑，没必要八卡的

**Comment by kkkwjr** [comment]
> 你好，无法正常推理是什么意思，其实一卡就能跑，没必要八卡的

作者大大我想问一下，如果说想把数字人做成实时的需要从哪些方面对代码或者模型进行改进呢，比如说量化啊什么的。
