### ISSUE TITLE
我发现 app_img.py  会身体动作，但是下单身就不兼容了~~

### ISSUE THREAD

**Issue by gg22mm** [Kedreamix/Linly-Talker#103]
我发现 app_img.py  会身体动作，但是下半身就不兼容了~~ ， 只能用 crop 模式
![1727148421560](https://github.com/user-attachments/assets/3a5c95f4-1e2c-44fd-9148-db65dd1b0627)

**Comment by Kedreamix** [comment]
你好，下半身不兼容是什么问题，我可能没有很get到你的意思，是下半身不动还是？

**Comment by gg22mm** [comment]
> 到你的意思，是下半

看看脖子那里，头与身体错位~~

**Comment by Kedreamix** [comment]
对于sadtalker来说，可以设置still参数保持静止的操作的

**Comment by gg22mm** [comment]
非常感谢~~~ ！
