### ISSUE TITLE
分离多个说话人 失败，不知道为啥出来就是一个人

### ISSUE THREAD

**Issue by nishengdu** [Kedreamix/Linly-Talker#113]
![image](https://github.com/user-attachments/assets/21dbab39-06d3-46cb-99e6-915168d1f7b1)
视频里有两个人说话，一个人不录脸，都是男性，另外一个视频是一男一女，最终都是只有第一个人发言的声音被使用念了全部的内容

**Comment by nishengdu** [comment]
![29ccb39cbc7d79bbc476cace3bd2cb6](https://github.com/user-attachments/assets/9ffd279d-ba7e-4c9e-bb00-8f77c93f7c6c)
修改为FunASR成功了，

**Comment by Kedreamix** [comment]
好的，感谢你的关注，这其实是他们分离说话人的能力的问题，不一定都非常好，我后续会探究他们的能力来进行解决
