### ISSUE TITLE
CosyVoice导入失败，

### ISSUE THREAD

**Issue by Crescentz** [Kedreamix/Linly-Talker#117]
CosyVoice导入失败，原因： During ast indexing the file /root/miniconda3/lib/python3.8/site-packages/modelscope/models/audio/aec/layers/activations.py, a related error excepted in the file /root/miniconda3/lib/python3.8/site-packages/modelscope/utils/ast_utils.py at line: 151: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file /root/miniconda3/lib/python3.8/site-packages/modelscope/models/audio/aec/layers/activations.py to see whether the file is correctly edited.

**Comment by Kedreamix** [comment]
你好，用最新的看看，用py 310k看看
