### ISSUE TITLE
什么是NeRFTalk

### ISSUE THREAD

**Issue by vonchenplus** [Kedreamix/Linly-Talker#124]
我看Nerf方案从ER-NeRF改为NeRFTalk，这里的NeRFTalk有具体的论文吗？还是说只是将ER-NeRF的名字改成了NeRFTalk？

**Comment by Kedreamix** [comment]
我结合改进了一下，本来想做一个NeRFTalk的项目，但是没来得及，我在最近会尽快更新，或者换成SyncTalk之类的方式
