### ISSUE TITLE
 pip install -r VITS/requirements_gptsovits.txt安装报错

### ISSUE THREAD

**Issue by hao203** [Kedreamix/Linly-Talker#17]
按照你的说明，安装这个的时候依赖出了问题
pip install -r VITS/requirements_gptsovits.txt

>  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [63 lines of output]
      Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
      Ignoring oldest-supported-numpy: markers 'python_version < "3.9"' don't match your environment
      ERROR: Exception:
      Traceback (most recent call last):

**Comment by Kedreamix** [comment]
从这里我认为可能是两种可能：
1. 可能是设置的pip源导致问题，换一下其他的源看看
2. 是不是numpy的包的版本导致问题
如果都有问题，可以考虑直接安装原作者的环境https://github.com/RVC-Boss/GPT-SoVITS， 再安装Linly-Talker，不过理论上是等价的

**Comment by hao203** [comment]
> 从这里我认为可能是两种可能：
> 
> 1. 可能是设置的pip源导致问题，换一下其他的源看看
> 2. 是不是numpy的包的版本导致问题
>    如果都有问题，可以考虑直接安装原作者的环境[https://github.com/RVC-Boss/GPT-SoVITS，](https://github.com/RVC-Boss/GPT-SoVITS%EF%BC%8C) 再安装Linly-Talker，不过理论上是等价的

感谢您的回复。

**Comment by FangXxun** [comment]
pip install -r VITS/requirements_gptsovits
我也遇到这个问题了
不过错误是
  LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”

**Comment by Kedreamix** [comment]
@FangXxun ，这可能是win的一些问题，可以参考https://blog.csdn.net/vah101/article/details/130548135
