### ISSUE TITLE
run app_img.py error!

### ISSUE THREAD

**Issue by OpenSorceYCW** [Kedreamix/Linly-Talker#20]
config.py unchanged.
import gradio as gr
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7890/')
Looking forward to your letter to resolving this issue.

**Comment by Kedreamix** [comment]
It's possible that your computer itself has set up a proxy 7890 for Clash. 
You can choose to turn off the proxy and then run it again.
