### ISSUE TITLE
LLM对话步骤出现错误：“对不起，你的请求出错了，请再次尝试。”

### ISSUE THREAD

**Issue by CarlosDJY** [Kedreamix/Linly-Talker#22]
您好，我在使用webui时上传语音对话，识别完成后提交视频时发生了如下的问题。
使用的显卡为4090。

错误部分如下：
extern "C"
__launch_bounds__(512, 4)
__global__ void reduction_prod_kernel(ReduceJitOp r){
  r.run();
}
nvrtc: error: invalid value for --gpu-architecture (-arch)

对不起，你的请求出错了，请再次尝试。
Sorry, your request has encountered an error. Please try again.

函数 predict 运行时间： 3.0960586071014404 秒
函数 LLM_response 运行时间： 3.160871982574463 秒
audio2exp:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 212.45it/s]Face Renderer:: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 92/92 [00:18<00:00,  5.00it/s]fps:  20 183
./results/temp_girl_answer.mp4
函数 Talker_response 运行时间： 22.409300565719604 秒

我的Qwen文件夹结构如下：
![image](https://github.com/Kedreamix/Linly-Talker/assets/103446832/58f866e3-2888-4a31-9d10-9490514293bc)

希望能帮忙解答，谢谢！

**Comment by Kedreamix** [comment]
这一部分应该是Qwen大模型的部分，是不是环境并没有安装正确，可以再看看Qwen的安装步骤是否正常

**Comment by zhangyue2709** [comment]
我也遇到了这样的问题，请问您怎么解决的呢

**Comment by zhangyue2709** [comment]
> 重新安装Qwen部分看看能不能解决 @zhangyue2709
> 
> pip install transformers==4.32.0 accelerate tiktoken einops scipy transformers_stream_generator==0.0.4 peft deepspeed

重新装一下就解决了，多谢啦
