### ISSUE TITLE
up主可以在语言克隆模块中加入RVC（简版SOVITS）项目嘛ㅠㅠ 

### ISSUE THREAD

**Issue by junjundaidai** [Kedreamix/Linly-Talker#23]
sovits运行时一直报错了。。可能RVC会更好跑通一点..？（）

**Comment by junjundaidai** [comment]
> 但我认为，做一个好的语音克隆，而不是随便做一个
> 
> 可以阵源项目的安装部分，希望也有一些一键安装包https://github.com/RVC-Boss/GPT-SoVITS

好滴，谢谢大佬！！(●'◡'●)

**Comment by Kedreamix** [comment]
其次也可以看看XTTS的方式，可能好安装一点
