### ISSUE TITLE
"i got an error when options preprocess --full without --still"这个错误貌似仍存在

### ISSUE THREAD

**Issue by zjzkiss** [Kedreamix/Linly-Talker#24]
原Issues地址
https://github.com/OpenTalker/SadTalker/issues/268

我看作者回复尽快修改，但是该bug至今仍是open的
有哪位大神解决了吗？

**Comment by Kedreamix** [comment]
如果是本身的问题话，可能还没解决

**Comment by Kedreamix** [comment]
full和still还是能解决的
