### ISSUE TITLE
  gr.Error("无克隆环境或者无克隆模型权重，无法克隆声音", e)

### ISSUE THREAD

**Issue by junjundaidai** [Kedreamix/Linly-Talker#25]
事先在单独工作区中训练了GPTsoVITS，然后再将训练好的权重放在了GPT_weights和SoVITS_weights中，然后运行克隆声音时出现以下error:

**/Linly-Talker/webui.py", line 114, in LLM_response
    gr.Error("无克隆环境或者无克隆模型权重，无法克隆声音", e)
TypeError: Error.__init__**

或许声音克隆这个模块在webui.py中还需要改代码吗？

**Comment by Kedreamix** [comment]
可以看看终端的报错，是不是环境没有安装好，权重下载正确了是么

**Comment by junjundaidai** [comment]
> 可以看看终端的报错，是不是环境没有安装好，权重下载正确了是么

谢谢大佬！ 我把ffmpeg卸载重新安装后可以运行了！！

**Comment by Kedreamix** [comment]
好！！！那可能是ffmpeg的问题
