### ISSUE TITLE
当我运行python webui.py ，并点击提交视频生成时，我遇到了Connection errored out

### ISSUE THREAD

**Issue by zhangyue2709** [Kedreamix/Linly-Talker#27]
![bf12c00f0e19a321e32a387cc17188f](https://github.com/Kedreamix/Linly-Talker/assets/137603553/bc4c14dc-5ff7-4d63-bf32-9340d087d43c)

终端如下图

![image](https://github.com/Kedreamix/Linly-Talker/assets/137603553/61e14ca3-0ebe-4285-b3b2-caccf244f10a)
 
请问各位大佬是什么原因呢

**Comment by Kedreamix** [comment]
这个可能是一些win的一些连接问题，其实蛮奇怪的，可能你二次运行又可以了，可以查一下相关资料，我暂时还没有遇到过

**Comment by zhangyue2709** [comment]
> 这个可能是一些win的一些连接问题，其实蛮奇怪的，可能你二次运行又可以了，可以查一下相关资料，我暂时还没有遇到过

 感谢作者回复，找到原因了，就是有些东西没装
