### ISSUE TITLE
API

### ISSUE THREAD

**Issue by hjh0915** [Kedreamix/Linly-Talker#29]
大佬，什么时候能开放API出来哇？（坐等中...

**Comment by Kedreamix** [comment]
什么API呢，可能不一定会开放，因为需要比较多的资源哈哈

**Comment by hjh0915** [comment]
哈哈～主要是本地电脑跑不动一点，就想着问问看大佬会不会出api的接口，这样可以试试看啦～～

**Comment by hjh0915** [comment]
哈哈～主要是本地电脑跑不动一点，就想着问问看大佬会不会出api的接口，这样可以试试看啦～～

**Comment by Kedreamix** [comment]
可以尝试使用google的colab来跑一下，我已经写好了代码，可以使用google的免费gpu来进行部署，不过可能就是稍微慢一点而已
