### ISSUE TITLE
运行报错 python app.py

### ISSUE THREAD

**Issue by diaojunxian** [Kedreamix/Linly-Talker#3]
你好，请教一个问题，项目根目录运行的时候会报这个错。

![image](https://github.com/Kedreamix/Linly-Talker/assets/19700467/2aba30f5-a04b-4379-b71e-ecd93182748a)

**Comment by Kedreamix** [comment]
已解决，是一个导入库的问题，重新提交了以下代码，可以尝试一下，修改一下LLM.py的代码即可
