### ISSUE TITLE
关于数字人的问题

### ISSUE THREAD

**Issue by 20246688** [Kedreamix/Linly-Talker#30]
请问我想传入一段话让数字人读，怎么实现？

**Comment by Kedreamix** [comment]
我还没加入口播的功能，这一部分很好实现，就是可以不经过LLM，直接把文字传给数字人即可

**Comment by 20246688** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kedreamix/Linly-Talker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月8日(星期一) 凌晨0:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kedreamix/Linly-Talker] 关于数字人的问题 (Issue #30)





 
我还没加入口播的功能，这一部分很好实现，就是可以不经过LLM，直接把文字传给数字人即可
