### ISSUE TITLE
启动webui.py报错：SadTalker Error:  invalid load key, 'v'.

### ISSUE THREAD

**Issue by wufxgtihub123** [Kedreamix/Linly-Talker#32]
我已经下载SadTalker的相关权重，保持和如下一致：
![image](https://github.com/Kedreamix/Linly-Talker/assets/74227869/0f48f636-6cc8-4bd3-b25d-cdce5e1dff0b)
但是我运行程序的时候还是报错了：
![image](https://github.com/Kedreamix/Linly-Talker/assets/74227869/de7a68a4-b5ac-496d-b3b9-8d96ed4d4faf)
是模型的权重文件下载得不对吗？请问该从哪里下载正确的文件？

**Comment by Kedreamix** [comment]
可以看看文件的大小，我怀疑是下载的时候，文件的大小是错误的，没有下载正确，下载路径有三个，可以替换有关sadtalker的部分即可
[Baidu (百度云盘)](https://pan.baidu.com/s/1eF13O-8wyw4B3MtesctQyg?pwd=linl) (Password: linl)
[huggingface](https://huggingface.co/Kedreamix/Linly-Talker)
[modelscope](https://www.modelscope.cn/models/Kedreamix/Linly-Talker/summary)

**Comment by wufxgtihub123** [comment]
> 可以看看文件的大小，我怀疑是下载的时候，文件的大小是错误的，没有下载正确，下载路径有三个，可以替换有关sadtalker的部分即可 [Baidu (百度云盘)](https://pan.baidu.com/s/1eF13O-8wyw4B3MtesctQyg?pwd=linl) (Password: linl) [huggingface](https://huggingface.co/Kedreamix/Linly-Talker) [modelscope](https://www.modelscope.cn/models/Kedreamix/Linly-Talker/summary)
很奇怪，我利用git lfs install 从你给的modelscope上下载权重，并且比对过大小没问题，但是还是报同样的错误，这很奇怪，和我使用的是torch2.0以上的版本有关吗？

**Comment by Kedreamix** [comment]
应该不是的，奇怪，还出问题么

**Comment by Kedreamix** [comment]
xd，后面我仔细看了以后，你可以关注一下mapping的两个文件，应该就是下载的时候，这两个文件很奇怪，有时候没有被下载下来，更新一下这两个文件即可
