### ISSUE TITLE
请问可以实现和数字人实时交流？

### ISSUE THREAD

**Issue by 641402676** [Kedreamix/Linly-Talker#33]
请问可以实现用rtmp_streaming推流，让数字人实时动起来然后实时交流吗？

**Comment by Kedreamix** [comment]
理论上是没有问题的哈哈，这一部分也有尝试在做

**Comment by 641402676** [comment]
> 理论上是没有问题的哈哈，这一部分也有尝试在做

我想实现的效果是   上传一张照片后，进行一个实时推流   然后进行一个实时的问答交流，但是目前还没找到方法实现

**Comment by Kedreamix** [comment]
是的，我也希望是类似的效果，其实简单来说，就是可以考虑socket通信做实时流这一部分，思路应该清晰，不过类似于工程实现
