### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by JackieGLQ** [Kedreamix/Linly-Talker#34]
(LinlyTalkerLaoGao) E:\GaoLLM\Test\LinlyTalkerLaoGao\Linly-Talker>pip install -r VITS/requirements_xtts.txt
Collecting TTS@ git+https://github.com/coqui-ai/TTS@v0.21.1 (from -r VITS/requirements_xtts.txt (line 2))
  Cloning https://github.com/coqui-ai/TTS (to revision v0.21.1) to c:\users\administrator\appdata\local\temp\pip-install-y6ubg7yq\tts_3702a0838f9d47cabc5e0cc2d313aefa
  Running command git clone --filter=blob:none --quiet https://github.com/coqui-ai/TTS 'C:\Users\Administrator\AppData\Local\Temp\pip-install-y6ubg7yq\tts_3702a0838f9d47cabc5e0cc2d313aefa'
  Running command git checkout -q 00a870c26abdc06429ffef3e2814b1a1d5b40fff
  Resolved https://github.com/coqui-ai/TTS to commit 00a870c26abdc06429ffef3e2814b1a1d5b40fff
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic==1.10.13 (from -r VITS/requirements_xtts.txt (line 3))
  Downloading pydantic-1.10.13-cp310-cp310-win_amd64.whl.metadata (150 kB)
     ---------------------------------------- 150.9/150.9 kB 1.8 MB/s eta 0:00:00
Collecting python-multipart==0.0.6 (from -r VITS/requirements_xtts.txt (line 4))
  Downloading python_multipart-0.0.6-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\anaconda3\envs\linlytalkerlaogao\lib\site-packages (from -r VITS/requirements_xtts.txt (line 5)) (4.11.0)
Collecting cutlet (from -r VITS/requirements_xtts.txt (line 6))
  Downloading cutlet-0.4.0.tar.gz (412 kB)
     ---------------------------------------- 412.3/412.3 kB 12.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting mecab-python3==1.0.6 (from -r VITS/requirements_xtts.txt (line 7))
  Downloading mecab_python3-1.0.6-cp310-cp310-win_amd64.whl.metadata (6.3 kB)
Collecting unidic-lite==1.0.8 (from -r VITS/requirements_xtts.txt (line 8))
  Downloading unidic-lite-1.0.8.tar.gz (47.4 MB)
     ---------------------------------------- 47.4/47.4 MB 17.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting unidic==1.1.0 (from -r VITS/requirements_xtts.txt (line 9))
  Downloading unidic-1.1.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: langid in e:\anaconda3\envs\linlytalkerlaogao\lib\site-packages (from -r VITS/requirements_xtts.txt (line 10)) (1.1.6)
Collecting deepspeed (from -r VITS/requirements_xtts.txt (line 11))
  Downloading deepspeed-0.14.2.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 14.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      系统找不到指定的文件。
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-y6ubg7yq\deepspeed_72617cae880f4f1d8e6c1569fd949e57\setup.py", line 190, in <module>
          ext_modules.append(builder.builder())
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-y6ubg7yq\deepspeed_72617cae880f4f1d8e6c1569fd949e57\op_builder\builder.py", line 659, in builder
          extra_link_args=self.strip_empty_entries(self.extra_ldflags()))
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-y6ubg7yq\deepspeed_72617cae880f4f1d8e6c1569fd949e57\op_builder\inference_cutlass_builder.py", line 71, in extra_ldflags
          import dskernels
      ModuleNotFoundError: No module named 'dskernels'
      DS_BUILD_OPS=1
      [93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
      [93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [93m [WARNING] [0m cpu_adam requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_adam requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adam attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_adagrad requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_adagrad requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_adagrad attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_lion requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m cpu_lion requires the 'lscpu' command, but it does not exist!
      [93m [WARNING] [0m cpu_lion attempted to query 'lscpu' after failing to use py-cpuinfo to detect the CPU architecture. 'lscpu' does not appear to exist on your system, will fall back to use -march=native and non-vectorized execution.
      [93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
      [93m [WARNING] [0m Filtered compute capabilities ['6.0', '6.1', '7.0']
      [93m [WARNING] [0m Filtered compute capabilities ['6.0', '6.1', '7.0']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(LinlyTalkerLaoGao) E:\GaoLLM\Test\LinlyTalkerLaoGao\Linly-Talker>conda install -c conda-forge

CondaValueError: too few arguments, must supply command line package specs or --file

**Comment by Kedreamix** [comment]
emmmmm，这个应该是dskernels库并没有安装正确，可以尝试使用,pip install dskernels 来安装缺失的库
