### ISSUE TITLE
使用full模式报错

### ISSUE THREAD

**Issue by wenjinliu** [Kedreamix/Linly-Talker#42]
使用full模式提示：RuntimeError: Given groups=1, weight of size [1024, 70, 7], expected input[1, 73, 27] to have 70 channels, but got 73 channels instead。

**Comment by Kedreamix** [comment]
最新的代码已经OK了，这其实是因为导入的模型错了，后续会更新到镜像中

**Comment by Kedreamix** [comment]
最新代码都已经完全OK了，可以试一下，镜像也更新了
