### ISSUE TITLE
能调ollama嘛？本地算力不够，需要调远程算力

### ISSUE THREAD

**Issue by kevinchi8781** [Kedreamix/Linly-Talker#45]

**Comment by Kedreamix** [comment]
可以的，加入一下LLM的部分就OK了

**Comment by kevinchi8781** [comment]
> 可以的，加入一下LLM的部分就OK了

docker部署，如何指定到ollama的地址，例如  192.168.12.114:11434

**Comment by Kedreamix** [comment]
可能这个得给你一个调用的模版给我，我才方便，理论上直接使用request库，可以参考问题汇总的方法加入LLM

**Comment by Kedreamix** [comment]
常用问题汇总中有给出关于ChatGPT的API的调用方式，可以尝试写一个去对应ollama来在Linly-Talker中使用，并且我加入了GPT4Free，能够免费试用API，感谢你的提问
