### ISSUE TITLE
我用WEBUI启动，似乎是用CPU在推理数字人视频！

### ISSUE THREAD

**Issue by wanlichina** [Kedreamix/Linly-Talker#46]
我用源码在WINDOWS机器用CONDA环境部署的，运行WEBUI.PY，跑到face renderer那一步的时候发现很慢，然后GPU没有占用都是CPU，是需要在哪里打开调用GPU开关吗？

**Comment by Kedreamix** [comment]
GPU部分是主要借助于PyTorch，所以要下载GPU版本的Pytorch即可自动调用了

**Comment by wanlichina** [comment]
我后来重新部署了一遍环境，按你流程里面给的命令，是以GPU版本的PYTORCH运行的。
之前那次变成了CPU版本的，可能的原因是不知道后面的哪个依赖把GPU版本的覆盖成了CPU版本的。
