### ISSUE TITLE
作者对展厅数字人有什么建议吗？

### ISSUE THREAD

**Issue by who0sy** [Kedreamix/Linly-Talker#48]
作者好，有个问题想请教下，我想基于这个项目做一个3d的问答虚拟数字人，就是那种可以放到展厅来实时对话，就调用在线的gpt api就行，有可能实现吗？ 
我理解是不是从问答到驱动数字人回答这个项目都集成了，我只需要更多的关注怎么用设备去承载数字人去展示就可以了？

**Comment by Kedreamix** [comment]
我觉得OK，但是可能可以的，然后还有就是看看界面方面自己决定怎么做，但是我觉得功能是比较完善的了，而且证明可以走通的
