### ISSUE TITLE
sadTalker下载的脚本没找到

### ISSUE THREAD

**Issue by HHaidai** [Kedreamix/Linly-Talker#49]
bash scripts/sadtalker_download_models.sh  
没有在源码中见到这个脚本文件

**Comment by Kedreamix** [comment]
你好，我后续加入了所有模型的下载脚本，在scripts下面有一个download_models.sh

**Comment by HHaidai** [comment]
好的谢谢，建议在readme中修改一下

**Comment by Kedreamix** [comment]
好的，感谢你的建议！
