### ISSUE TITLE
页面出来就是连接到网络，这什么情况

### ISSUE THREAD

**Issue by hfutly66** [Kedreamix/Linly-Talker#5]
打开网页之后，会出现连接到网络需要登录，然后跳转http://edge-http.microsoft.com/captiveportal/generate_204
http://www.gstatic.com/generate_204
![Snipaste_2024-01-17_11-44-26](https://github.com/Kedreamix/Linly-Talker/assets/60588672/4848698e-bd0f-481c-8795-d18355b0a14f)

**Comment by Kedreamix** [comment]
方便的话，看看后台显示什么，一般是显示要出现一个0.0.0.0:7870，0.0.0.0换为自己的IP地址即可

**Comment by hfutly66** [comment]
搞不太懂，sd和大语言模型都可以用，这个不行
![image](https://github.com/Kedreamix/Linly-Talker/assets/60588672/9649bc48-84f0-433e-afbe-4e170dee1b76)
