### ISSUE TITLE
执行 pip install -r requirements_webui.txt 时候报错

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Talker#51]
ERROR: Could not find a version that satisfies the requirement tb-nightly (from basicsr) (from versions: none)
ERROR: No matching distribution found for tb-nightly

**Comment by Kedreamix** [comment]
tb-nightly可能不同的源是有问题的，清华源可能会出现问题，可尝试使用阿里云源
`pip install tb-nightly -i https://mirrors.aliyun.com/pypi/simple`

**Comment by anstonjie** [comment]
好的谢谢
