### ISSUE TITLE
运行python app_musetalk.py 报错 MuseTalk的相关模型我都已经下载完了，为啥运行musetalk需要ERNeRF的环境 不理解

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Talker#52]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4'
ERNeRF导入失败，原因： list index out of range
使用ERNeRF前需要安装对应的环境
MuseTalk导入失败，原因： DLL load failed while importing _ext: 找不到指定的模块。
使用MuseTalk前需要安装对应的环境
MuseTalk Error: cannot import name 'MuseTalk_RealTime' from 'TFG' (D:\ai3\Linly-Talker\TFG\__init__.py)
如果使用MuseTalk，请先下载MuseTalk相关模型
Traceback (most recent call last):
  File "D:\ai3\Linly-Talker\app_musetalk.py", line 195, in <module>
    demo = main()
  File "D:\ai3\Linly-Talker\app_musetalk.py", line 78, in main
    source_video.change(fn=musetalker.prepare_material, inputs=[source_video, bbox_shift], outputs=[source_video, bbox_shift_scale])
NameError: name 'musetalker' is not defined

**Comment by anstonjie** [comment]
是不是必须用cu118 但是用了CU118那个ERNERF的 pip install "git+https://github.com/facebookresearch/pytorch3d.git" 这个就执行不成功

**Comment by Kedreamix** [comment]
这个其实跟cuda的关系没有那么大，但是对于环境的设置比较大，建议是暂时别用ERNeRF，我个人认为在Linux中NeRF报错的概率比较小。
然后看你这个问题，应该是有些环境没有安装成功

**Comment by Kedreamix** [comment]
主要问题应该在于`DLL load failed while importing ext: 找不到指定的模块。`中，初步来看，应该是mmdet, mmcv, mmpose的部分库并没有正确安装，可以尝试重新安装MuseTalk的相关库即可正常运行

```
# 安装有关musetalk依赖
pip install --no-cache-dir -U  openmim
mim install mmengine 
mim install "mmcv>=2.0.1" 
mim install "mmdet>=3.1.0" 
mim install "mmpose>=1.1.0" 
```

**Comment by tianyaXs** [comment]
> 是不是必须用cu118 但是用了CU118那个ERNERF的 pip install "git+https://github.com/facebookresearch/pytorch3d.git" 这个就执行不成功

解决了没有，遇到了同样的问题
