### ISSUE TITLE
上传视频格式问题

### ISSUE THREAD

**Issue by chenshiyia** [Kedreamix/Linly-Talker#55]
你好，请问使用musetalk的时候，上传的视频有固定格式要求吗，为什么我的总报错呢
![a8afc9be-1cc5-42a9-a6ec-a3f943b8ebf3](https://github.com/Kedreamix/Linly-Talker/assets/76093562/0bd5238c-8bd0-469e-b7a5-2b3411ec853d)

**Comment by Kedreamix** [comment]
你上传的是musev生成的视频吗
看起来预处理正常的 是不是也有可能上传的视频没有人脸呢

**Comment by chenshiyia** [comment]
不是musev生成的视频，是外部导入的O.o

**Comment by Kedreamix** [comment]
我个人认为可能视频的某些帧有问题，导致不好，建议是使用MuseV生成的

**Comment by 2twentyto2** [comment]
大佬请问怎么解决的呢，是对上传的视频有要求还是需要进行代码的修改
