### ISSUE TITLE
你好我想问一下Linly-Talker-win-all的museTalk怎么跑不起来啊

### ISSUE THREAD

**Issue by 3165523246** [Kedreamix/Linly-Talker#57]
你好我想问一下Linly-Talker-win-all的museTalk怎么跑不起来啊
![image](https://github.com/Kedreamix/Linly-Talker/assets/116544481/05e2d2a2-84e2-4491-a1ba-1eca6f04b7c5)

**Comment by zhlgx** [comment]
![PixPin_2024-06-25_13-03-36](https://github.com/Kedreamix/Linly-Talker/assets/56181415/65e2c7d7-71d4-4751-82f9-ee56873f70b0)
也不知道哪里不对，完全根据步骤走的，也不行！

**Comment by 3165523246** [comment]
兄弟加个微信一起讨论一下 V :   wxid_9c4pyghxd3z322

**Comment by 3165523246** [comment]
> ![PixPin_2024-06-25_13-03-36](https://private-user-images.githubusercontent.com/56181415/342623569-65e2c7d7-71d4-4751-82f9-ee56873f70b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMDM0NzEsIm5iZiI6MTcxOTMwMzE3MSwicGF0aCI6Ii81NjE4MTQxNS8zNDI2MjM1NjktNjVlMmM3ZDctNzFkNC00NzUxLTgyZjktZWU1Njg3M2Y3MGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDA4MTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhY2ZmMmYyODRjMzExMjNlMmE4ZjRmNGVhNjI1NzJjMjQ1ZTc2YzRhNzE4YjNiMWEzM2M1Yjk0YjdjZmJmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TcHlV_8uN0j9BY9ty7EYHttgnCx2ItcV6V4X520LCqQ) 也不知道哪里不对，完全根据步骤走的，也不行！

兄弟加个微信一起讨论一下 V : wxid_9c4pyghxd3z322

**Comment by Kedreamix** [comment]
可以试一下进行激活环境以后再安装一下musetalk的依赖，或者这几天我会尝试更新一下

**Comment by araya** [comment]
已解决，是环境的问题引起的 mmcv的问题

**Comment by 3165523246** [comment]
> 已解决，是环境的问题引起的 mmcv的问题
怎么解决的

**Comment by Ankitjaiswal1201** [comment]
So I had the same issue, and this is how i resolved it:

First I uninstalled all the package related to mmcv

`
pip uninstall mmdet mmpose mmengine mmcv 
pip cache purge
`

And then installed specific versions of all the packages. For me the following package versions worked:
`
mim install mmengine  
mim install "mmcv==2.1.0"
mim install "mmdet==3.2.0" 
mim install "mmpose==1.2.0" 
`

And then again you can run the python webui.py, the issue should be resolved
