### ISSUE TITLE
这个proxy url要如何设置

### ISSUE THREAD

**Issue by lucasjinreal** [Kedreamix/Linly-Talker#6]
需要单独构建一个魔法server吗

**Comment by Kedreamix** [comment]
这个是给了一个选择出来，我觉得可能有人使用GeminiPro的时候，可能会使用到代理，所以我给了一个参数。
这个参数设置应该是http://ip:port，如果本地就是http://127.0.0.1:7890，我这里写7890是因为我使用到是clash转发端口，可改
