### ISSUE TITLE
  你好，非常感谢你们提供的项目，我使用你们通过的docker镜像执行python webui.py之后，在前端选择GPT-SoVITS会出现错误，请问能否帮忙解答一下

### ISSUE THREAD

**Issue by xuquankun** [Kedreamix/Linly-Talker#62]
file "/root/Linly-Talker/webui.py", line 127, in TTS_response     gr.Warning("无克隆环境或者无克隆模型权重，无法克隆声音", e)

**Comment by Kedreamix** [comment]
感谢你的关注，你好，我觉得我需要更多详细一点报错内容，要不有点难为你解决问题

**Comment by xuquankun** [comment]
谢谢你的回复，我找到了问题的所在，是我忘记加载模型了
