### ISSUE TITLE
windows系统编译NeRF失败如何处理

### ISSUE THREAD

**Issue by liaoqingjian** [Kedreamix/Linly-Talker#63]
# 注意以下几个模块，若安装不成功，可以进入路径利用pip install . 或者 python setup.py install编译安装
# NeRF/freqencoder
# NeRF/gridencoder
# NeRF/raymarching
# NeRF/shencoder
使用上面作者的编译方式，我使用windows系统编译NeRF失败，导致运行后界面里面生成数字人视频失败，请问作者我该如何处理，怎么解决windows系统编译NeRF失败的问题

**Comment by Kedreamix** [comment]
你好，感谢你的提问，对于NeRF环境的一些设置，我个人建议给出编译报错的问题，或者可以查看问题汇总来进行解决

**Comment by LiWeisuper** [comment]
(linly) PS E:\AI\Linly_Talker> pip install NeRF/freqencoder
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing e:\ai\linly_talker\nerf\freqencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: freqencoder
  Building wheel for freqencoder (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freqencoder
  Running setup.py clean for freqencoder
Failed to build freqencoder
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (freqencoder)

**Comment by Kedreamix** [comment]
这个问题我也并没有找到对应的解决方法，我建议还是在Linux上进行
