### ISSUE TITLE
大佬要不建个微信交流群

### ISSUE THREAD

**Issue by TnoobT** [Kedreamix/Linly-Talker#67]
大佬要不要建个微信交流群，大家一起交流一下数字人啊

**Comment by Kedreamix** [comment]
你好，我已经建立啦！！！可以看看那个问题汇总最后

**Comment by Tiandishihua** [comment]
> 大佬要不要建个微信交流群，大家一起交流一下数字人啊

您好！能拉我进数字群交流一下吗？谢谢

**Comment by Tiandishihua** [comment]
> 你好，我已经建立啦！！！可以看看那个问题汇总最后
您好！能拉我进数字群交流一下吗？谢谢
