### ISSUE TITLE
用docker拉取下来启动问题

### ISSUE THREAD

**Issue by we1chao** [Kedreamix/Linly-Talker#69]
这个是什么没加载成功呢？
![PixPin_2024-07-15_21-23-46](https://github.com/user-attachments/assets/8c1e29a3-1891-4e07-a3c5-9189bfea3c49)

**Comment by we1chao** [comment]
![Uploading PixPin_2024-07-15_21-23-46.png…]()

**Comment by Kedreamix** [comment]
你好，感谢你的关注，你这个可能是因为share=True的原因，你可以调节这个参数，变成share=False尝试一下
