### ISSUE TITLE
Musetalk不显示（小白求教）

### ISSUE THREAD

**Issue by do-one-thing-to-well** [Kedreamix/Linly-Talker#70]
我按照README里的集成步骤，在`autodl`上将项目运行起来，但是发现，在`webui`中并没有`musetalk`的选项，我也下载了`musetalk`模型了，如下图：  
![微信截图_20240717104832](https://github.com/user-attachments/assets/9f6d431b-64cb-4d1c-9477-adce66ee24c2)

然后在`webui`的效果，如下图：

![微信截图_20240717104759](https://github.com/user-attachments/assets/b2ab9a32-1563-4fc5-ba0e-6fc2d1717ed3)

请问作者，我这是哪里出问题了？

**Comment by do-one-thing-to-well** [comment]
还有，请问如何调节生成视频的清晰度

**Comment by do-one-thing-to-well** [comment]
musetalk不显示是因为mmcv版本过高，
期待版本：>=2.0.0 && < 2.2.0  
我的mmcv版本>2.2.0
但是我使用`pip install mmcv==2.0.0`或 `pip install mmcv==2.1.0`一大堆报错。。。

**Comment by Kedreamix** [comment]
你好，我一一回复你的问题

1. 首先第一个问题，我最新的代码里面，MuseTalk是其中一个tab选项，所以不会在这里面选择，从上面的tab标签页中选取即可
2. 第二个问题，生成视频的清晰度来源于输入视频的清晰度，也会更具清晰度占据更多的显存，这里面有一个权衡
3. 第三个问题，musetalk不显示是因为没使用对tab，可以安装我指定的版本即可，你可以安装对应的mmcv和版本即可

**Comment by do-one-thing-to-well** [comment]
好的，感谢大佬，回复的很及时。
