### ISSUE TITLE
api的问题

### ISSUE THREAD

**Issue by lxb0425** [Kedreamix/Linly-Talker#74]
有没有api接入到其他系统 
webui.py
app.py
启动的是界面 
有没有接口传入图片 文本生成视频回来的那种

**Comment by Kedreamix** [comment]
后续我会加入API的实现，现在API的实现只有LLM的部分

**Comment by lgx-19981103** [comment]
同问，我在Linly-api-fast.py中发现只有一个接口，是不是就是作者说的LLM的部分

**Comment by lgx1103** [comment]
> 有没有api接入到其他系统 webui.py app.py 启动的是界面 有没有接口传入图片 文本生成视频回来的那种

我使用fastapi写了一个脚本，可以通过输入图片、发音人、文字来生成数字人视频，如有需要，+q1373942050

**Comment by lgx1103** [comment]
我使用fastapi写了一个脚本，可以通过输入图片、发音人、文字来生成数字人视频，如有需要+我

**Comment by Kedreamix** [comment]
已经更新API文档，欢迎使用
