### ISSUE TITLE
gr.Audio的音频时常问题

### ISSUE THREAD

**Issue by maxchiron** [Kedreamix/Linly-Talker#75]
作者您好，最近我也在写类似该项目的实现，同样出现了gr.Audio获取input audio时长大于10秒后，报错，后端无法获取到input audio。

请问您知道是什么原因吗？有解决方案或思路吗？谢谢🙏

**Comment by Kedreamix** [comment]
你好，这里其实是基于GPT-SoVITS的方法实现的，他的一些标准其实是希望3～10s的短音频，要不然可能会出现一些error，我们可以去掉这些判断即可

**Comment by maxchiron** [comment]
> 你好，这里其实是基于GPT-SoVITS的方法实现的，他的一些标准其实是希望3～10s的短音频，要不然可能会出现一些error，我们可以去掉这些判断即可

感谢大佬回复，学习了~
我这边的问题也找到了，是nginx的配置问题，增大file size就行了，谢谢。
