### ISSUE TITLE
现在是否已经添加了对视频字幕的实现？

### ISSUE THREAD

**Issue by chentiejin1** [Kedreamix/Linly-Talker#76]

**Comment by Kedreamix** [comment]
视频字幕目前能生成每一段的文字，可以加入到视频里面，在b站视频的展示等都能看的出来

**Comment by Kedreamix** [comment]
如果希望能够单独生成字幕，我也会做一下这个测试，只是觉得这个可以直接生成了，如果单独生成可以用funasr直接生成的
