### ISSUE TITLE
性能很差 有什么办法吗

### ISSUE THREAD

**Issue by lxb0425** [Kedreamix/Linly-Talker#79]
我需要实现一个与LLM交互的数字虚拟人，到时候显示在手机上
计划是LLM回复生成数据人视频响应到前端，但是视频生成时间太长了 有什么方案吗
![image](https://github.com/user-attachments/assets/d9e970d9-5787-47d0-a8b3-36c231cad95c)

而且生成的视频惨不忍睹 /捂脸
![image](https://github.com/user-attachments/assets/d21691d6-eee8-4e3d-8051-99d7eccdb05c)

**Comment by Kedreamix** [comment]
这个效果应该是没有设置好 是自定义角色的效果吗 由于是生成完展示结果的 所以可能需要改成流式可能能加快响应速度

**Comment by lxb0425** [comment]
自定义上传了图片 哪里没设置好啊 应该改那些参数
现在支持流式吗 ？我使用时qwen2模型 扩展了api

**Comment by Kedreamix** [comment]
你好，可以关注我的视频操作部分，现在暂时不支持流式，应该是不和Qwen有关系的
