### ISSUE TITLE
python app_img.py 生成视频的话，每次都会报错

### ISSUE THREAD

**Issue by 499909744** [Kedreamix/Linly-Talker#8]
python app_img.py 生成视频的话，每次都会报这种错， app.py 和 app_multi.py启动后是好着的
![image](https://github.com/Kedreamix/Linly-Talker/assets/16700590/9a1a4137-85b7-4b04-accf-b5d8e61f2a70)

**Comment by 499909744** [comment]
pirender_checkpoint参数对应的文件也下载到对应的目录下了,  https://huggingface.co/vinthony/SadTalker-V002rc/resolve/main/epoch_00190_iteration_000400000_checkpoint.pt

**Comment by Kedreamix** [comment]
我看了看，我觉得可能是因为文件的问题，就是可能是因为下载的时候中断或者什么原因，导致可能出现了问题。建议重新下载一下，我也给了百度网盘链接 https://pan.baidu.com/s/1eF13O-8wyw4B3MtesctQyg?pwd=linl ，可以重新下载一下
