### ISSUE TITLE
安装到pip install -r TFG/requirements_nerf.txt报错，按照方法解决不了

### ISSUE THREAD

**Issue by hjj-lmx** [Kedreamix/Linly-Talker#81]
pip install -r TFG/requirements_nerf.txt

# If you encouter issues with pyaudio
sudo apt-get update
sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

# Note the following modules. If installation fails, you can enter the directory and use pip install . or python setup.py install to compile and install:
# NeRF/freqencoder
# NeRF/gridencoder
# NeRF/raymarching
# NeRF/shencoder

**Comment by Kedreamix** [comment]
你好 具体什么问题

**Comment by hjj-lmx** [comment]
> 你好 具体什么问题

  Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.linux-x86_64-cpython-38/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/src
      creating build/temp.linux-x86_64-cpython-38/src/pyaudio
      gcc -pthread -B /home/vipuser/anaconda3/envs/linly/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -I/usr/include -I/home/vipuser/anaconda3/envs/linly/include/python3.8 -c src/pyaudio/device_api.c -o build/temp.linux-x86_64-cpython-38/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: portaudio.h: No such file or directory
          9 | #include "portaudio.h"
            |          ^~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
  Building wheel for freqencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.8/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for freqencoder
  Running setup.py clean for freqencoder
  Building wheel for gridencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.8/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gridencoder
  Running setup.py clean for gridencoder
  Building wheel for raymarching-face (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.8/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for raymarching-face
  Running setup.py clean for raymarching-face
  Building wheel for shencoder (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.8/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for shencoder
  Running setup.py clean for shencoder
Failed to build pyaudio freqencoder gridencoder raymarching-face shencoder
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyaudio, freqencoder, gridencoder, raymarching-face, shencoder)

**Comment by hjj-lmx** [comment]
> 你好 具体什么问题

如果是启动app_talk,
(linly) root@ubuntu20:/usr/local/Linly-Talker# python app_talk.py
PaddleTTS Error:  No module named 'paddlespeech'
如果使用PaddleTTS，请先安装PaddleTTS环境
pip install -r requirements_paddle.txt
Using cuda for inference.
ERNeRF导入失败，原因： No module named 'mcubes'
使用ERNeRF前需要安装对应的环境
Loads checkpoint by local backend from path: ./Musetalk/models/dwpose/dw-ll_ucoco_384.pth
using safetensor as default
Load checkpoint from: checkpoints/wav2lip_gan.pth
ERNeRF Error:  No module named 'mcubes'
如果使用ERNeRF，请先下载ERNeRF模型
PaddleTTS Error:  No module named 'paddlespeech'
如果使用PaddleTTS，请先下载PaddleTTS模型
Running on local URL:  https://0.0.0.0:8801

To create a public link, set `share=True` in `launch()`.

但是我访问不到页面

**Comment by Kedreamix** [comment]
这个已经成功了，可以访问https://[你的IP地址]:8801即可
