### ISSUE TITLE
python webui后，控制台显示

### ISSUE THREAD

**Issue by hjj-lmx** [Kedreamix/Linly-Talker#82]
PaddleTTS Error:  No module named 'paddlespeech'
如果使用PaddleTTS，请先安装PaddleTTS环境
pip install -r requirements_paddle.txt
默认不使用LLM模型，直接回复问题，同时减少显存占用！
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
GPT_SoVITS导入失败，原因： 
**********************************************************************
  Resource cmudict not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('cmudict')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/cmudict

  Searched in:
    - '/root/nltk_data'
    - '/home/vipuser/anaconda3/envs/linly/nltk_data'
    - '/home/vipuser/anaconda3/envs/linly/share/nltk_data'
    - '/home/vipuser/anaconda3/envs/linly/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

使用GPT-SoVITS语音克隆前需要安装对应的环境，请执行 pip install -r VITS/requirements_vits.txt
2024-08-06 15:57:47,324 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-08-06 15:57:47,325 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-08-06 15:57:47,502 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 3b8301012bd8861a176e84c3e4705143 and a total number of 946 components indexed
CosyVoice导入成功
GPT-SoVITS 加载失败: name 'GPT_SoVITS' is not defined
如果使用VITS，请先下载GPT-SoVITS模型并安装环境
Using cuda for inference.
ERNeRF导入失败，原因： No module named 'trimesh'
使用ERNeRF前需要安装对应的环境
Loads checkpoint by local backend from path: ./Musetalk/models/dwpose/dw-ll_ucoco_384.pth
using safetensor as default
Success! SadTalker模块加载成功，默认使用SadTalker模型
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
100%|████████████████████████████████████████| 139M/139M [06:38<00:00, 364kiB/s]
Success! WhisperASR模块加载成功，默认使用Whisper-base模型
Success! MuseTalk模块加载成功
Running on local URL:  http://0.0.0.0:8801

请问一下，这里还需要安装什么？

**Comment by Kedreamix** [comment]
你好 你这个其实已经安装完成了 但是由于网络问题 nltk并没有下载成功 所以报错
建议是换个网络 或者 查看问题汇总中的办法 将提供的nltk下载下来放在指定位置即可
