### ISSUE TITLE
并发问题

### ISSUE THREAD

**Issue by lgx1103** [Kedreamix/Linly-Talker#83]
我现在的项目可能需要多线程去生成数字人，请问支持并发吗？或者有队列处理

**Comment by Kedreamix** [comment]
在gradio中可能是不行的，但是实际上程序是可以支持并发的，不过有可能占用的显存会多一点，类似于同时做
但是其实我现在还没有做并发的操作，但是gradio默认是有一些的，但是可能不稳定
后续我实现api的时候，我会尝试并发，但是其实是可以的，支持的
