### ISSUE TITLE
docker pull registry.cn-beijing.aliyuncs.com/codewithgpu2/kedreamix-linly-talker:zYGdW3yO3D出现下面错误，是正常现象吗？

### ISSUE THREAD

**Issue by hjj-lmx** [Kedreamix/Linly-Talker#84]
failed to register layer: write /root/Linly-Talker/Musetalk/models/musetalk/pytorch_model.bin: no space left on device

**Comment by Kedreamix** [comment]
你好，这个是因为，docker会放在你的系统盘下，可能镜像太大了，占据的位置太多了，导致系统没有足够的空间了，这个其实是硬盘内存的问题
可以通过`df -h`看硬盘情况
