### ISSUE TITLE
请问 wav2lipv2.pth、yolov8n-face.pt 等模型文件有吗，哪里可以下载？

### ISSUE THREAD

**Issue by lemwang** [Kedreamix/Linly-Talker#86]
![image](https://github.com/user-attachments/assets/b241a8d8-e53e-4026-88f3-c02049f9b56d)

**Comment by lemwang** [comment]
找到了，谢谢！

**Comment by liuyp28** [comment]
请问wav2lipv2.pth在哪里下载吗

**Comment by verigle** [comment]
> 请问wav2lipv2.pth在哪里下载吗

同问

**Comment by Kedreamix** [comment]
@liuyp28 @verigle 可以从这里下载，我也会更新一下其他下载方式的模型 [https://modelscope.cn/models/Kedreamix/Linly-Talker](https://modelscope.cn/models/Kedreamix/Linly-Talker)
