### ISSUE TITLE
如果采用实时流式对话模式，对硬件环境有什么具体要求？

### ISSUE THREAD

**Issue by JerryDaHeLian** [Kedreamix/Linly-Talker#89]
比如：运行系统最低配要求是，GPU型号？内存大小？显存大小？cpu型号？硬盘大小？操作系统？等等

**Comment by Kedreamix** [comment]
其实运行系统没有最低要求，最低要求可能是显存6g或者8g吧，支持数字人的生成即可
因为大模型可能可以通过api规避掉显存使用，TTS也可以用微软的，操作系统是建议使用Linux的，感谢你的提问
当然，如果硬件越好有可能在推理的时候速度会越快
