### ISSUE TITLE
如何通过docker compose 启动镜像

### ISSUE THREAD

**Issue by verigle** [Kedreamix/Linly-Talker#91]
registry.cn-beijing.aliyuncs.com/codewithgpu2/kedreamix-linly-talker:zYGdW3yO3D

如何通过docker compose 启动镜像呢？

**Comment by JerryDaHeLian** [comment]
同问！有教程吗？

**Comment by Kedreamix** [comment]
docker的教程可以从网上找一下，这个部分我可能也不能太帮助你，应该是可以直接拉镜像即可的
