### ISSUE TITLE
[W] [service.go:132] login to server failed: EOF报错，有大佬知道怎么解决吗

### ISSUE THREAD

**Issue by kkkwjr** [Kedreamix/Linly-Talker#93]
(LinlyTalk) wpg@node7gpu:/workspace/kkkjr/Item/Linly-Talker$ python app.py
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
[nltk_data] Error loading cmudict: <urlopen error [Errno 111]
[nltk_data]     Connection refused>
Using cuda for inference.
Loads checkpoint by local backend from path: ./Musetalk/models/dwpose/dw-ll_ucoco_384.pth
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.19steps/s]
using safetensor as default
_______________________++++++++++++++++++++++++++++++++++++
布局已完成
Running on local URL:  https://0.0.0.0:7870
2024/08/27 07:07:38 [W] [service.go:132] login to server failed: EOF

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

**Comment by kkkwjr** [comment]
import gradio as gr
print("11111111111111111111111111")
def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=True,server_name="0.0.0.0")

在linux中运行这个简单的可以成功

**Comment by kkkwjr** [comment]
解决了似乎将   ssl_verify设置为True就可以了

 demo.launch(server_name=ip, # 本地端口localhost:127.0.0.1 全局端口转发:"0.0.0.0"
                server_port=port,
                # 似乎在Gradio4.0以上版本可以不使用证书也可以进行麦克风对话
                # ssl_certfile=ssl_certfile,
                # ssl_keyfile=ssl_keyfile,
                ssl_verify=True,
                debug=True,
                # share=True
                )

**Comment by Kedreamix** [comment]
这个有点奇怪，理论上不应该是ssl的问题，不过解决了就好，我个人认为有可能是share的问题之类的
