### ISSUE TITLE
无法找到麦克风

### ISSUE THREAD

**Issue by Rockycocky** [Kedreamix/Linly-Talker#94]
![image](https://github.com/user-attachments/assets/ddfccf29-962d-477d-ae07-848cb7ad0144)

**Comment by JerryDaHeLian** [comment]
遇到同样的问题。

**Comment by JerryDaHeLian** [comment]
我是通过docker装的环境，也遇到“无法找到麦克风”问题，解决办法如下：
https://github.com/Kedreamix/Linly-Talker/blob/main/docs/Certificate.md
按照这个网址尝试生成ssl证书，然后将webui.py中的：
 ssl_certfile=ssl_certfile, 
 ssl_keyfile=ssl_keyfile,  
 ssl_verify=False,
取消上述三个变量的注释，访问网址由http://改为https://。

**Comment by Kedreamix** [comment]
@JerryDaHeLian 感谢您的解答，希望对您有帮助 @Rockycocky

**Comment by Rockycocky** [comment]
根据@JerryDaHeLian提供的方法 问题解决

**Comment by Crescentz** [comment]
> ![image](https://private-user-images.githubusercontent.com/10336965/362211954-ddfccf29-962d-477d-ae07-848cb7ad0144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDI0MDEsIm5iZiI6MTczMDU0MjEwMSwicGF0aCI6Ii8xMDMzNjk2NS8zNjIyMTE5NTQtZGRmY2NmMjktOTYyZC00NzdkLWFlMDctODQ4Y2I3YWQwMTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEwMDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTUwMjBkNzI1MDllMjFjYzRjOTliMTQ3MDMzMGU2NjgyY2VmZWE3YzIzMjZmNDllMzUzMWJiY2NmZGY4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E5sOksSMjFlkIaOfSY56aCvpj398vPyYJE7qhfwoUV4)

请问，pull之后，怎么运行的，请问你的运行命令
