### ISSUE TITLE
在webui界面操作后，后台报错pydantic.errors.PydanticSchemaGenerationErro

### ISSUE THREAD

**Issue by WSXDM2024** [Kedreamix/Linly-Talker#99]
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
![image](https://github.com/user-attachments/assets/2b7d6c72-d137-45d3-8221-8b3d3a36f02c)

**Comment by gg22mm** [comment]
运行python webui.py时出现 pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class starlette.requests.Request>错误
解决：是Gradio版本的问题，默认会安装最新版。使用4.43.0版可以解决。
% pip install -U gradio==4.43.0

我看网上是这样说的

**Comment by Kedreamix** [comment]
感谢你的回答， @WSXDM2024 也可以看看有没有用处，是否能解决，因为我可能没有遇到过这样的问题
